# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 零组文库签到
on:
  schedule:
    - cron: "0 0 8 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Set Up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install requests==2.23.0
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Get Setting
        env:
          PUSHTYPE: ${{secrets.PUSHTYPE}}
          DINGTALKACCESSTOKEN: ${{secrets.DINGTALKACCESSTOKEN}}
          FTSERVERKEY: ${{secrets.FTSERVERKEY}}
          TELEGRAMTOKEN: ${{secrets.TELEGRAMTOKEN}}
          TELEGRAMCHADID: ${{secrets.TELEGRAMCHADID}}
          BARKTOKEN: ${{secrets.BARKTOKEN}}
          BARKSERVER: ${{secrets.BARKSERVER}}
          PLUSPUSH: ${{secrets.PLUSPUSH}}
          EWECHATPUSHTOKEN: ${{secrets.EWECHATPUSHTOKEN}}
          EWECHATAGENTID: ${{secrets.EWECHATAGENTID}}
          EWECHATAPPSECRETS: ${{secrets.EWECHATAPPSECRETS}}
          VCUSER: ${{secrets.VCUSER}}
          VCPASS: ${{secrets.VCPASS}}
          ZSECWIKIUSER: ${{secrets.ZSECWIKIUSER}}
          ZSECWIKIPASS: ${{secrets.ZSECWIKIPASS}} 
        run: |
          python3 0secSign.py
