# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 零组文库签到
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
         python -m pip install --upgrade pip
         pip install 
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Setting
      run: |
        PUSHTYPE:${{secrets.PUSHTYPE}}
        DINGTALKACCESSTOKEN:${{secrets.DINGTALKACCESSTOKEN}}
        FTSERVERKEY:${{secrets.FTSERVERKEY}}
        TELEGRAMTOKEN:${{secrets.TELEGRAMTOKEN}}
        TELEGRAMCHADID:${{secrets.TELEGRAMCHADID}}
        BARKTOKEN:${{secrets.BARKTOKEN}}
        BARKSERVER:${{secrets.BARKSERVER}}
        PLUSPUSH:${{secrets.PLUSPUSH}}
        EWECHATPUSHTOKEN:${{secrets.EWECHATPUSHTOKEN}}
        EWECHATAGENTID:${{secrets.EWECHATAGENTID}}
        EWECHATAPPSECRETS:${{secrets.EWECHATAPPSECRETS}}
        VCUSER:${{secrets.VCUSER}}
        VCPASS:${{secrets.VCPASS}}
        ZSERCIKIUSER:${{secrets.ZSERCIKIUSER}}
        ZSECWIKIPASS:${{secrets.ZSECWIKIPASS}}
        python3 0secSign.py
 
